server:
  port: 9101

spring:
  datasource:
    password:
    testWhileIdle: true
    url: jdbc:mysql://localhost:3306/jwt-service-db?useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  prefix: /api
  routes:
    product:
      path: /products/**
      url: http://localhost:9990/api/products
    category:
      path: /categories/**
      url: http://localhost:9990/api/categories
    department:
      path: /departments/**
      url: http://localhost:9990/api/departments
    review:
      path: /reviews/**
      url: http://localhost:9990/api/reviews
    customer:
      path: /customers/**
      url: http://localhost:9992/api/customers

